Add --scan-between functionality.

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -12,9 +12,12 @@
 # express or implied. See the License for the specific language governing
 # permissions and limitations under the License.
 
+# shellcheck disable=SC2155
+
 NONGIT_OK=1 OPTIONS_SPEC="\
 git secrets --scan [-r|--recursive] [--cached] [--no-index] [--untracked] [<files>...]
 git secrets --scan-history
+git secrets --scan-between [hashA..hashB]
 git secrets --install [-f|--force] [<target-directory>]
 git secrets --list [--global]
 git secrets --add [-a|--allowed] [-l|--literal] [--global] <pattern>
@@ -24,6 +27,7 @@ git secrets --aws-provider [<credentials-file>]
 --
 scan Scans <files> for prohibited patterns
 scan-history Scans repo for prohibited patterns
+scan-between Scans the repo for prohibited patterns between two given commit hashes
 install Installs git hooks for Git repository or Git template directory
 list Lists secret patterns
 add Adds a prohibited or allowed pattern, ensuring to de-dupe with existing patterns
@@ -104,6 +108,48 @@ scan_history() {
   # Scan through revisions with findings to normalize output
   output=$(GREP_OPTIONS= LC_ALL=C git grep -nwHEIP "${combined_patterns}" $to_scan)
   process_output $? "${output}"
+}
+
+# Takes an argument like commitHashA..commitHashB
+# Scans modified files in each commit at each point in history
+scan_between() {
+  # Fail if unstaged changes exist
+  git update-index --refresh
+  [[ -n $(git status --porcelain=v1 2>/dev/null) ]] &&
+    echo "Commit or stash changes first." && exit 1
+
+  # Require scan range (HEAD/head or SHA1 hash)
+  # Abbreviated hashes minimum 7 chars allowed
+  local -r scan_range="${1}"
+  head_or_sha1="(HEAD|head|[0-9a-f]{7,40})(\^[0-9]{1})?"
+  [[ ! ${scan_range} =~ ^${head_or_sha1}[\.]{2,3}${head_or_sha1}$ ]] &&
+    printf "Must specify a valid scan range, i.e. 'gitHashA..gitHashB'" >&2 && exit 1
+
+  # No patterns means nothing to scan for (OK)
+  local combined_patterns=$(load_combined_patterns)
+  [ -z "${combined_patterns}" ] && return 0
+
+  # No commits means nothing to scan (OK)
+  local -r commits_cmd="git log ${scan_range} --format=format:%h --reverse"
+  IFS=$'\n' read -r -d '' -a commits < <( ${commits_cmd} && printf '\0' )
+  [ -z "${commits}" ] && return 0
+  unset IFS
+
+  local -r current_branch=$(git branch --show-current)
+
+  declare found
+  for commit_hash in "${commits[@]}"; do
+    git checkout "${commit_hash}" >& /dev/null
+    local prev_commit_hash=$(git rev-parse "${commit_hash}^1")
+    local files_changed=$(git diff "${prev_commit_hash}..${commit_hash}" --name-only)
+    local buff=$(GREP_OPTIONS= LC_ALL=C git grep -nwHEIP \ "${combined_patterns}" -- ${files_changed} | sed "s/^/${commit_hash}:/")
+    [[ -n ${buff} ]] && found+=$(echo -e "\r\n${buff}")
+    unset buff
+  done
+
+  git switch "${current_branch}" >& /dev/null
+  [[ -n ${found} ]] && status=0 || status=1
+  process_output "${status}" "${found}"
 }
 
 # Performs a git-grep, taking into account patterns and options.
@@ -336,6 +382,7 @@ case "${COMMAND}" in
     ;;
   --scan) scan_with_fn_or_die "scan" "$@" ;;
   --scan-history) scan_with_fn_or_die "scan_history" "$@" ;;
+  --scan-between) scan_with_fn_or_die "scan_between" "$@" ;;
   --list)
     if [ ${GLOBAL} -eq 1 ]; then
       git config --global --get-regex secrets.*
